server:
  address: 0.0.0.0
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: asror0812@gmail.com
    password: mknb upzz zcxw fnzw

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  upload-dir: uploads
