ALTER TABLE chats
DROP CONSTRAINT IF EXISTS chat_type_check;

ALTER TABLE chats
DROP CONSTRAINT IF EXISTS chats_type_check;

ALTER TABLE chats
ADD CONSTRAINT chats_type_check
CHECK (type IN ('TEACHER_GROUP', 'STUDENT_GROUP', 'SUBJECT_GROUP', 'DIRECT'));