name: Build and Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          cache-dependency-path: |
            build.gradle
            settings.gradle
            gradle/wrapper/gradle-wrapper.properties

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build executable JAR with Gradle
        run: ./gradlew clean bootJar -x test --no-daemon

      - name: Clean backend folder on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /opt/backend
            sudo rm -f /opt/backend/*.jar

      - name: Copy JAR to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "/opt/backend/"
          strip_components: 2

      - name: Restart Systemd Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            JAR_FILE=$(ls /opt/backend/*.jar | grep -v plain | head -n 1)

            if [ -z "$JAR_FILE" ]; then
              echo "No executable JAR found"
              exit 1
            fi


            sudo cp "$JAR_FILE" /opt/backend/app.jar
            sudo systemctl restart api.rspcm.service
            sleep 15
            sudo systemctl status api.rspcm.service --no-pager